apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

helmCharts:
- name: base
  releaseName: istio-base
  includeCRDs: true
  version: 1.15.1
  namespace: istio-system
  repo: https://istio-release.storage.googleapis.com/charts